# Generated by Django 3.1.2 on 2021-09-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dutyStation', models.CharField(max_length=128)),
                ('salary', models.CharField(max_length=64)),
                ('experience', models.CharField(max_length=64)),
                ('education', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('companyType', models.CharField(max_length=128)),
                ('companyScale', models.CharField(max_length=64)),
                ('technology', models.CharField(max_length=256)),
                ('jobLabel', models.CharField(max_length=256)),
            ],
        ),
    ]
