# Generated by Django 3.1.2 on 2021-09-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210913_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=64, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyScale',
            field=models.CharField(max_length=64, verbose_name='公司规模'),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyType',
            field=models.CharField(max_length=128, verbose_name='公司类型'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dutyStation',
            field=models.CharField(max_length=128, verbose_name='工作地点'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(max_length=64, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=64, verbose_name='经验'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobLabel',
            field=models.CharField(max_length=256, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=128, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=64, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='job',
            name='technology',
            field=models.CharField(max_length=256, verbose_name='技术需求'),
        ),
    ]
